export const FETCH_CATEGORY_DATA = 'category/FETCH_DATA';
export const FETCH_CATEGORY_DATA_SUCCESSFUL = 'category/FETCH_DATA_SUCCESSFUL';
export const FETCH_CATEGORY_DATA_FAILED = 'category/FETCH_DATA_FAILED';
